package View;
import java.util.Hashtable;
import javax.swing.JPanel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.event.*;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bl
 */
public class settings extends javax.swing.JPanel {
    JFrame frame;
    JPanel menu;

    /**
     * Creates new form settings
     */
    public settings(JFrame f, JPanel menu) {
        frame = f;
        this.menu = menu;
        initComponents();
    }

    public void updateSettings(JPanel menu) {
        this.menu = menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        starter = new javax.swing.JComboBox<>();
        Player1 = new javax.swing.JComboBox<>();
        Player2 = new javax.swing.JComboBox<>();
        starterlabel = new javax.swing.JLabel();
        player2txt = new javax.swing.JLabel();
        player1txt = new javax.swing.JLabel();
        difficulty_txt = new javax.swing.JLabel();
        Apply = new javax.swing.JLabel();
        cancel_par = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        background = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 720));
        setLayout(null);

        starter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yellow", "Black" }));
        add(starter);
        starter.setBounds(490, 220, 170, 24);

        Player1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Human", "Ai" }));
        add(Player1);
        Player1.setBounds(490, 290, 170, 24);

        Player2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Human", "Ai" }));
        add(Player2);
        Player2.setBounds(490, 360, 170, 24);

        starterlabel.setIcon(new javax.swing.ImageIcon("/home/bl/Bureau/Fanorona-main/src/View/ressources/starter.png")); // NOI18N
        add(starterlabel);
        starterlabel.setBounds(170, 200, 250, 65);

        player2txt.setIcon(new javax.swing.ImageIcon(("/home/bl/Bureau/Fanorona-main/src/View/ressources/player2.png"))); // NOI18N
        add(player2txt);
        player2txt.setBounds(170, 340, 250, 60);

        player1txt.setIcon(new javax.swing.ImageIcon(("/home/bl/Bureau/Fanorona-main/src/View/ressources/player1.png"))); // NOI18N
        add(player1txt);
        player1txt.setBounds(170, 270, 250, 60);

        difficulty_txt.setIcon(new javax.swing.ImageIcon(("/home/bl/Bureau/Fanorona-main/src/View/ressources/difficulty.png"))); // NOI18N
        add(difficulty_txt);
        difficulty_txt.setBounds(170, 410, 250, 60);

        Apply.setIcon(new javax.swing.ImageIcon(("/home/bl/Bureau/Fanorona-main/src/View/ressources/apply.png"))); // NOI18N
        add(Apply);
        Apply.setBounds(475, 480, 100, 109);
        Apply.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                frame.getContentPane().removeAll();
                frame.add(menu);
                frame.setVisible(true);
                frame.repaint();
            }

        });

        cancel_par.setIcon(new javax.swing.ImageIcon(("/home/bl/Bureau/Fanorona-main/src/View/ressources/cancel.png"))); // NOI18N
        add(cancel_par);
        cancel_par.setBounds(250, 480, 100, 110);
        cancel_par.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                frame.getContentPane().removeAll();
                frame.add(menu);
                frame.setVisible(true);
                frame.repaint();
            }

        });

        jLabel1.setIcon(new javax.swing.ImageIcon(("/home/bl/Bureau/Fanorona-main/src/View/ressources/settings_title.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(350, 20, 99, 103);

        jSlider1.setMajorTickSpacing(50);
        jSlider1.setMinorTickSpacing(50);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Hashtable position = new Hashtable();
        position.put(0, new JLabel("Easy"));
        position.put(50, new JLabel("medium"));
        position.put(100, new JLabel("hard"));

        // Set the label to be drawn
        jSlider1.setLabelTable(position);
        add(jSlider1);
        jSlider1.setBounds(450, 420, 200, 42);

        background.setIcon(new javax.swing.ImageIcon(("/home/bl/Bureau/Fanorona-main/src/View/ressources/2512129.jpg"))); // NOI18N
        add(background);
        background.setBounds(0, 0, 800, 720);
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel Apply;
    private javax.swing.JComboBox<String> Player1;
    private javax.swing.JComboBox<String> Player2;
    private javax.swing.JLabel background;
    private javax.swing.JLabel cancel_par;
    private javax.swing.JLabel difficulty_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel player1txt;
    private javax.swing.JLabel player2txt;
    private javax.swing.JComboBox<String> starter;
    private javax.swing.JLabel starterlabel;
    // End of variables declaration                   
}
